#include<stdio.h>
#include<conio.h>
void main()
{

clrscr();
	int rows;
	int collums;
	int k=1;

	printf("enter the number of rows : ");
	scanf("%d",&rows);

	printf("en
	ter the number of collums : ");
	scanf("%d",&rows);
	int a[rows][collums];
		int i=1;
	while(i<=rows)
		{
		int j=1;
		      while(i<=collums)
		      {
			 printf("%d/t",k);
			 k++;
			 j++;
		      }
		      i++;
		      printf("\n");
		}
	getch();
	}

